In [9]:
from class_feature_engin import feature_engineering as fe
from class_feature_engin import S_learner
import pandas as pd
from sklearn.linear_model import LogisticRegression
import feature_engineering as ff

In [18]:
df_funct = ff.read_in_and_get_ready('Hillstrom.csv', include_treatment=True)
df_funct

(        recency   history mens womens newbie  zip_code_Rural  \
 0      0.603876 -0.194501    1      0      0               0
 1      0.033679  0.169807    1      1      1               1
 2      0.176229 -0.119918    0      1      1               0
 3      0.461327  0.846639    1      0      1               1
 4     -0.536517 -0.384034    1      0      0               0
 ...         ...       ...  ...    ...    ...             ...
 63995  0.603876 -0.266528    1      0      0               0
 63996 -0.108870 -0.396585    0      1      1               0
 63997  0.033679 -0.413996    1      0      1               0
 63998 -0.679066  0.606766    1      0      1               0
 63999 -0.679066  0.450377    0      1      0               0

        zip_code_Surburban  zip_code_Urban  channel_Multichannel  \
 0                       1               0                     0
 1                       0               0                     0
 2                       1               0                     0
 3                       0               0                     0
 4                       0               1                     0
 ...                   ...             ...                   ...
 63995                   0               1                     0
 63996                   0               1                     0
 63997                   0               1                     0
 63998                   1               0                     1
 63999                   1               0                     0

        channel_Phone  channel_Web  segment_0  segment_1  segment_2
 0                  1            0          0          1          0
 1                  0            1          1          0          0
 2                  0            1          0          1          0
 3                  0            1          0          0          1
 4                  0            1          0          1          0
 ...              ...          ...        ...        ...        ...
 63995              0            1          0          0          1
 63996              1            0          0          0          1
 63997              1            0          0          0          1
 63998              0            0          0          1          0
 63999              0            1          0          0          1

 [64000 rows x 14 columns],
 0        0
 1        0
 2        0
 3        0
 4        0
         ..
 63995    0
 63996    0
 63997    0
 63998    0
 63999    0
 Name: visit, Length: 64000, dtype: int64)

In [19]:
df_funct[0].columns

Index(['recency', 'history', 'mens', 'womens', 'newbie', 'zip_code_Rural',
       'zip_code_Surburban', 'zip_code_Urban', 'channel_Multichannel',
       'channel_Phone', 'channel_Web', 'segment_0', 'segment_1', 'segment_2'],
      dtype='object')

In [2]:
df = S_learner('Hillstrom.csv',LogisticRegression(random_state = 42),0.7,41)

In [17]:
df.data.columns

Index(['recency', 'history', 'mens', 'womens', 'newbie', 'visit',
       'zip_code_Rural', 'zip_code_Surburban', 'zip_code_Urban',
       'channel_Multichannel', 'channel_Phone', 'channel_Web', 'segment_0',
       'segment_1', 'segment_2'],
      dtype='object')

In [3]:
df.data

,recency,history,mens,womens,newbie,visit,zip_code_Rural,zip_code_Surburban,zip_code_Urban,channel_Multichannel,channel_Phone,channel_Web,segment_0,segment_1,segment_2
0,0.603876,-0.194501,1,0,0,0,0,1,0,0,1,0,1,0,0
1,0.033679,0.169807,1,1,1,0,1,0,0,0,0,1,0,0,1
2,0.176229,-0.119918,0,1,1,0,0,1,0,0,0,1,1,0,0
3,0.461327,0.846639,1,0,1,0,1,0,0,0,0,1,0,1,0
4,-0.536517,-0.384034,1,0,0,0,0,0,1,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63995,0.603876,-0.266528,1,0,0,0,0,0,1,0,0,1,0,1,0
63996,-0.108870,-0.396585,0,1,1,0,0,0,1,0,1,0,0,1,0
63997,0.033679,-0.413996,1,0,1,0,0,0,1,0,1,0,0,1,0
63998,-0.679066,0.606766,1,0,1,0,0,1,0,1,0,0,1,0,0
63999,-0.679066,0.450377,0,1,0,0,0,1,0,0,0,1,0,1,0

In [4]:
df.data.dtypes

recency                  float64
history                  float64
mens                    category
womens                  category
newbie                  category
visit                      int64
zip_code_Rural             uint8
zip_code_Surburban         uint8
zip_code_Urban             uint8
channel_Multichannel       uint8
channel_Phone              uint8
channel_Web                uint8
segment_0                  uint8
segment_1                  uint8
segment_2                  uint8
dtype: object

In [5]:
df._prepare_segments_test()
df.X_per_segment['segment_0_1']

,recency,history,mens,womens,newbie,zip_code_Rural,zip_code_Surburban,zip_code_Urban,channel_Multichannel,channel_Phone,channel_Web,segment_0,segment_1,segment_2
53141,0.033679,-0.002763,1,1,0,0,1,0,0,1,0,1,0,0
41451,0.888974,-0.187982,1,0,0,0,0,1,0,1,0,1,0,0
52631,0.461327,-0.344000,1,0,1,0,1,0,0,1,0,1,0,0
57484,0.176229,0.491192,0,1,0,0,1,0,1,0,0,1,0,0
2916,-0.536517,0.519183,1,0,1,0,1,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31855,0.461327,-0.413996,0,1,1,0,1,0,0,0,1,1,0,0
56858,-0.536517,0.052750,1,1,1,0,0,1,0,1,0,1,0,0
36176,0.603876,-0.413079,0,1,1,0,0,1,0,0,1,1,0,0
20371,-0.251419,0.163366,0,1,0,0,0,1,0,0,1,1,0,0
14812,0.603876,-0.070222,1,0,0,0,1,0,0,1,0,1,0,0

In [6]:
df.X_per_segment['segment_1_1']

,recency,history,mens,womens,newbie,zip_code_Rural,zip_code_Surburban,zip_code_Urban,channel_Multichannel,channel_Phone,channel_Web,segment_0,segment_1,segment_2
53141,0.033679,-0.002763,1,1,0,0,1,0,0,1,0,0,1,0
41451,0.888974,-0.187982,1,0,0,0,0,1,0,1,0,0,1,0
52631,0.461327,-0.344000,1,0,1,0,1,0,0,1,0,0,1,0
57484,0.176229,0.491192,0,1,0,0,1,0,1,0,0,0,1,0
2916,-0.536517,0.519183,1,0,1,0,1,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31855,0.461327,-0.413996,0,1,1,0,1,0,0,0,1,0,1,0
56858,-0.536517,0.052750,1,1,1,0,0,1,0,1,0,0,1,0
36176,0.603876,-0.413079,0,1,1,0,0,1,0,0,1,0,1,0
20371,-0.251419,0.163366,0,1,0,0,0,1,0,0,1,0,1,0
14812,0.603876,-0.070222,1,0,0,0,1,0,0,1,0,0,1,0

In [7]:
df.params

{}

In [8]:
df._run_predictions()

TypeError: '(slice(None, None, None), 1)' is an invalid key

In [ ]:
df.proba_per_segment

{'segment_0_1': array([[0.75793053, 0.24206947],
        [0.90743183, 0.09256817],
        [0.92978247, 0.07021753],
        ...,
        [0.91065021, 0.08934979],
        [0.78961867, 0.21038133],
        [0.88667507, 0.11332493]]),
 'segment_1_1': array([[0.71246517, 0.28753483],
        [0.8858155 , 0.1141845 ],
        [0.91288436, 0.08711564],
        ...,
        [0.88969408, 0.11030592],
        [0.74812712, 0.25187288],
        [0.86095438, 0.13904562]]),
 'segment_2_1': array([[0.83166071, 0.16833929],
        [0.93927479, 0.06072521],
        [0.95432394, 0.04567606],
        ...,
        [0.94145749, 0.05854251],
        [0.85553681, 0.14446319],
        [0.92506864, 0.07493136]])}